name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.1
        #   dest: # optional, default is ~/setup-pnpm
        #   run_install: # optional, default is null
        #   package_json_file: # optional, default is package.json
        #   standalone: # optional, default is false
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
